<<<<<<< HEAD:.github/workflows.yml/main.yml
name: Deploy to QA

concurrency: 1
=======
name: Deploy to stagin
>>>>>>> 0cd8488ef353462c846451a325ba1b9feaf58caf:.github/workflows/staging.yml

on:
  push:
    branches:
      - main # Set the branch you want to trigger the workflow for
  # pull_request:
  #   branches:
  #     - main
 

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main
      
<<<<<<< HEAD:.github/workflows.yml/main.yml
      - run: databricks bundle deploy -t QA
=======
      - run: databricks bundle deploy 
>>>>>>> 0cd8488ef353462c846451a325ba1b9feaf58caf:.github/workflows/staging.yml
        
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
         
          

  pipeline_update:
    name: "Run jobs "
    runs-on: self-hosted

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run jobs
<<<<<<< HEAD:.github/workflows.yml/main.yml
        run: databricks bundle run -t QA wheel-job 
=======
        run: databricks bundle run wheel-job 
>>>>>>> 0cd8488ef353462c846451a325ba1b9feaf58caf:.github/workflows/staging.yml
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
         
